; Scanner RSSI de répéteur MeshCore — Seeed Wio Tracker L1 Pro (nRF52840 + SX1262)
; La définition de carte (boards/) et la variante Arduino (variants/) sont
; reprises du firmware MeshCore (licence MIT), qui supporte officiellement
; cette carte. Le linker script place l'application après le SoftDevice
; S140 7.3.0 installé par le bootloader UF2 d'usine.
[env:wio_tracker_l1]
platform = nordicnrf52
board = seeed-wio-tracker-l1
framework = arduino
board_build.variants_dir = variants
board_build.ldscript = boards/nrf52840_s140_v7.ld
monitor_speed = 115200
lib_deps =
    jgromes/RadioLib@^7
    adafruit/Adafruit SH110X@^2.1
