#!/usr/bin/env bash
# Assembles the release binaries into dist/ after a `pio run`:
#  - ESP32 targets: merged "factory" image (bootloader + partition table
#    + boot_app0 + application), flashable at address 0x0 - this is the
#    format expected by flasher.meshcore.io and esptool;
#  - Wio Tracker L1: UF2 to drag and drop onto the bootloader drive.
# Usage: scripts/package.sh <version> [directory]
set -euo pipefail

VERSION="${1:?usage: package.sh <version> [directory]}"
DIST="${2:-dist}"
BUILD=.pio/build

# ESP32 tooling, only looked up when an ESP32 target was built (a job
# that built a single nRF52 target has neither esptool nor the ESP32
# framework package installed).
esp32_tools() {
  # esptool: pip module in CI, otherwise the one from the PlatformIO package
  if python3 -c 'import esptool' 2>/dev/null; then
    esptool() { python3 -m esptool "$@"; }
  else
    ESPTOOL_PY=$(ls "$HOME"/.platformio/packages/tool-esptoolpy*/esptool.py 2>/dev/null | head -1)
    [ -n "$ESPTOOL_PY" ] || { echo "esptool not found (pip install esptool)" >&2; exit 1; }
    esptool() { python3 "$ESPTOOL_PY" "$@"; }
  fi
  BOOT_APP0=$(ls "$HOME"/.platformio/packages/framework-arduinoespressif32*/tools/partitions/boot_app0.bin 2>/dev/null | head -1)
  [ -n "$BOOT_APP0" ] || { echo "boot_app0.bin not found" >&2; exit 1; }
}

mkdir -p "$DIST"
packaged=0

# ESP32 targets: every built environment that produced a bootloader.
# Full image with the "-merged.bin" suffix, which flasher.meshcore.io
# reads as "flash at 0x0 with erase" (without it, it would write the
# file at 0x10000 and the board would not boot).
# (`merge_bin`: alias accepted by esptool v4 - the local PlatformIO
# fallback - as well as v5, pinned in CI, where the canonical name is
# `merge-bin`.)
for bootloader in "$BUILD"/*/bootloader.bin; do
  [ -e "$bootloader" ] || continue
  [ -n "${BOOT_APP0:-}" ] || esp32_tools
  target=$(basename "$(dirname "$bootloader")")
  esptool --chip esp32s3 merge_bin \
    -o "$DIST/meshcaching-$target-$VERSION-merged.bin" \
    0x0 "$bootloader" \
    0x8000 "$BUILD/$target/partitions.bin" \
    0xe000 "$BOOT_APP0" \
    0x10000 "$BUILD/$target/firmware.bin"
  packaged=$((packaged + 1))
done

# nRF52 targets: every environment that produced a firmware.hex.
# Two formats: the DFU package (firmware.zip, generated by the
# nordicnrf52 platform) expected by flasher.meshcore.io and
# adafruit-nrfutil, and the UF2 for drag and drop onto the bootloader
# drive.
for hex in "$BUILD"/*/firmware.hex; do
  [ -e "$hex" ] || continue
  target=$(basename "$(dirname "$hex")")
  cp "$BUILD/$target/firmware.zip" "$DIST/meshcaching-$target-$VERSION.zip"
  python3 scripts/hex2uf2.py "$hex" \
    "$DIST/meshcaching-$target-$VERSION.uf2" \
    0xADA52840
  packaged=$((packaged + 1))
done

[ "$packaged" -gt 0 ] || { echo "no target built in $BUILD" >&2; exit 1; }
(cd "$DIST" && sha256sum meshcaching-* > SHA256SUMS)
ls -l "$DIST"
